### ISSUE TITLE
Refreshing pages don't work after navigating to lower-level url

### ISSUE THREAD

**Issue by mrjf** [forrestLyman/wordpress-ng#1]
If I click on a link and end up at, say:

http://my-url.com/page/foo

when I reload the page, I get a 404 because the web server can't actually find that page. Any way to avoid this behavior without making server-side changes?

Thanks!

**Comment by forrestLyman** [comment]
This is related to Angular's html5 mode. It provides cleaner URLs, but requires additional configuration. I just updated the demo site so it uses hashBang mode by default (/#!/path/to/page) so it works out of the box.

FYI here's some documentation on the different modes: https://docs.angularjs.org/guide/$location
