### ISSUE TITLE
Suggestion: tell users to make their wordpress.com site private, so that it doesn't get crawled twice

### ISSUE THREAD

**Issue by mrjf** [forrestLyman/wordpress-ng#2]
Having the same content visible under *.wordpress.com as well as the regular domain could result in a search engine penalty for duplicate content. You could suggest that users of this package make their wordpress.com sites private and unindexed.

This can be changed under settings by selecting:

Settings > Reading > Site Visibility >  I would like my site to be private, visible only to myself and users I choose

But then the API won't work. Is there a way to get authenticated API access? Checking this out...

**Comment by forrestLyman** [comment]
They support OAUTH2, which I am planning on integrating so we can access the protected endpoints (in place editing is on the roadmap). 

For the time being I use the 'Discourage search engines from indexing this site' option which adds a robots.txt file.
